package com.tencent.mm.storage;

import android.content.Context;
import com.tencent.mm.compatible.util.d;
import com.tencent.mm.sdk.platformtools.aa;

public final class j
{
  public static String bpc = d.bpc;
  public static final String kAH = aa.getContext().getFilesDir() + "/xlog";
  
  public static enum a
  {
    static
    {
      kBA = new a("USERINFO_VOICEPRINT_SETTING_ACCOUNT_INFO_NEW_SHOW_BOOLEAN", 44);
      kBB = new a("USERINFO_REPORTNETTYPE_SEQ_LONG", 45);
      kBC = new a("USERINFO_REPORTNETTYPE_LASTREPORT_LONG", 46);
      kBD = new a("USERINFO_SELFINFO_SMALLIMGURL_STRING", 47);
      kBE = new a("USERINFO_SELFINFO_GETPROFILE_TIME_LONG", 48);
      kBF = new a("USERINFO_WALLET_BALANCE_NOTICE_STRING", 49);
      kBG = new a("USERINFO_WALLET_FETCH_NOTICE_STRING", 50);
      kBH = new a("USERINFO_WALLET_SUPPORT_BANK_WORD_STRING", 51);
      kBI = new a("USERINFO_NEED_TO_UPDATE_CONVERSATION_TIME_DIVIDER_LONG", 52);
      kBJ = new a("USERINFO_EXPOSE_GETEXPOSESCENE_TIME_LONG", 53);
      kBK = new a("USERINFO_WXPHONE_PB_COUNT_INT", 54);
      kBL = new a("USERINFO_MALL_INDEX_HAS_SHOWN_FTF_NOTICE_BOOLEAN", 55);
      kBM = new a("USERINFO_PHONE_RECHARGE_CLOSED_BANNER_STRING", 56);
      kBN = new a("USERINFO_QQMAIL_UNREAD_COUNT_INT", 57);
      kBO = new a("USERINFO_AUTOGETBIG_IMG_MAX_LONG", 58);
      kBP = new a("USERINFO_AUTOGETBIG_IMG_CURRENT_LONG", 59);
      kBQ = new a("USERINFO_AUTOGETBIG_IMG_CURRENT_DATE_LONG", 60);
      kBR = new a("USERINFO_SHAKE_KV_STAT_BLUETOOTH_POWER_STATE_TIME_LONG", 61);
      kBS = new a("USERINFO_SHAKE_TV_LATITUDE_STRING", 62);
      kBT = new a("USERINFO_SHAKE_TV_LONGTITUDE_STRING", 63);
      kBU = new a("NEW_BANDAGE_DATASOURCE_NEW_CARD_REDDOT_WORDING_STRING_SYNC", 64);
      kBV = new a("NEW_BANDAGE_DATASOURCE_NEW_CARD_ICON_STRING_SYNC", 65);
      kBW = new a("NEW_BANDAGE_WATCHER_SETTING_CARD_ENTRY_REDDOT_WORDING_STRING_SYNC", 66);
      kBX = new a("NEW_BANDAGE_WATCHER_SETTING_CARD_ENTRY_ICON_STRING_SYNC", 67);
      kBY = new a("USERINFO_CARDLAYOUT_TESTDATA_STRING", 68);
      kBZ = new a("USERINFO_CARD_LAYOUT_BUF_DATA_STRING_SYNC", 69);
      kCa = new a("USERINFO_CARD_REDOT_WORDING_STRING_SYNC", 70);
      kCb = new a("USERINFO_CARD_REDOT_END_TIME_INT_SYNC", 71);
      kCc = new a("USERINFO_CARD_REDOT_BUFF_STRING_SYNC", 72);
      kCd = new a("USERINFO_CARD_REDOT_ICON_URL_STRING_SYNC", 73);
      kCe = new a("USERINFO_CARD_MSG_TIPS_TITLE_STRING_SYNC", 74);
      kCf = new a("USERINFO_CARD_MSG_TIPS_ICON_URL_STRING_SYNC", 75);
      kCg = new a("USERINFO_CARD_GET_LAYOUT_SCENE_INT_SYNC", 76);
      kCh = new a("USERINFO_CARD_GET_LAYOUT_JSON_STRING_SYNC", 77);
      kCi = new a("USERINFO_CARD_SHARECARD_LAYOUT_JSON_STRING_SYNC", 78);
      kCj = new a("USERINFO_CARD_REQUENCE_LONG_SYNC", 79);
      kCk = new a("USERINFO_CARD_IS_SHARE_CARD_ENTRANCE_OPEN_INT_SYNC", 80);
      kCl = new a("USERINFO_CARD_IS_SHOW_SHARE_CARD_TIP_INT_SYNC", 81);
      kCm = new a("USERINFO_CARD_IS_SHOW_SHARE_CARD_ENTRANCE_TIP_INT_SYNC", 82);
      kCn = new a("USERINFO_CARD_SHARE_LIST_CLEAR_TIME_INT_SYNC", 83);
      kCo = new a("USERINFO_CARD_SHOW_WARNING_CARD_IDS_STRING_SYNC", 84);
      kCp = new a("USERINFO_CARD_HAS_UPDATE_CARD_TYPE_INT_SYNC", 85);
      kCq = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_GUIDE_BOOLEAN_SYNC", 86);
      kCr = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_HWFPMANAGER_BOOLEAN_SYNC", 87);
      kCs = new a("USERINFO_WALLET_FINGERPRINT_SWITCH_IS_NOT_NEW_BOOLEAN_SYNC", 88);
      kCt = new a("USERINFO_FINGER_PRINT_IS_OPEN_BOOLEAN_SYNC", 89);
      kCu = new a("USERINFO_FINGER_PRINT_IS_SO_LOAD_SUCCESS_BOOLEAN_SYNC", 90);
      kCv = new a("USERINFO_FINGER_PRINT_IS_FORCE_PWD_MODE_BOOLEAN_SYNC", 91);
      kCw = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_GUIDE_IN_TRANSPARENT_BOOLEAN_SYNC", 92);
      kCx = new a("USERINFO_FINGER_PRINT_IS_SO_LOADLIBRARY_SUCCESS_BOOLEAN_SYNC", 93);
      kCy = new a("USERINFO_ABTEST_SERVER_TIMESTAMP_INT", 94);
      kCz = new a("USERINFO_ABTEST_LAST_UPDATE_TIME_LONG", 95);
      kCA = new a("USERINFO_ABTEST_UPDATE_TIME_INTERVAL_INT", 96);
      kCB = new a("USERINFO_NFC_CPU_CARD_CONFIG_STRING_SYNC", 97);
      kCC = new a("USERINFO_BIND_MOBILE_XML_TIP_BOOLEAN", 98);
      kCD = new a("USERINFO_BIND_MOBILE_XML_FORCE_BIND_BOOLEAN", 99);
      kCE = new a("USERINFO_BIND_MOBILE_XML_WORDING_STRING", 100);
      kCF = new a("USERINFO_BIZ_ATTR_SYNC_OPEN_FLAG_INT", 101);
      kCG = new a("USERINFO_NFC_OPEN_SWITCH_INT_SYNC", 102);
      kCH = new a("USERINFO_NFC_OPEN_DEFAULT_SWITCH_INT_SYNC", 103);
      kCI = new a("BUSINESS_SNS_ADLOG_FREQUENCY_INT", 104);
      kCJ = new a("BUSINESS_SNS_ADLOG_CNTTIME_INT", 105);
      kCK = new a("USERINFO_NFC_OPEN_SWITCH_WORDING_STRING_SYNC", 106);
      kCL = new a("USERINFO_IPCALL_COUNTRY_CODE_RESTRCTION_INT", 107);
      kCM = new a("USERINFO_IPCALL_COUNTRY_CODE_LASTUPDATE_TIME_LONG", 108);
      kCN = new a("USERINFO_IPCALL_FIRST_IN_BOOLEAN", 109);
      kCO = new a("USERINFO_IPCALL_ADDRESS_LASTREPORT_TIME_LONG", 110);
      kCP = new a("USERINFO_IPCALL_ADDRESS_GETMFRIEND_LASTUPDATE_TIME_LONG", 111);
      kCQ = new a("USERINFO_IPCALL_ADDRESS_GETLOCATION_LASTUPDATE_TIME_LONG", 112);
      kCR = new a("USERINFO_IPCALL_ADDRESS_ACCOUNT_SHOW_REDDOT_BOOLEAN", 113);
      kCS = new a("USERFINO_IPCALL_ADDRESS_ACCOUNT_SHOW_REDDOT_TYPE_INT", 114);
      kCT = new a("USERFINO_IPCALL_ADDRESS_ACCOUNT_STRING", 115);
      kCU = new a("USERFINO_IPCALL_RECHARGE_STRING", 116);
      kCV = new a("USERINFO_IPCALL_RECHARGE_SHOW_REDDOT_BOOLEAN", 117);
      kCW = new a("USERINFO_IPCALL_EXCHANGE_RECORD_SHOW_REDDOT_BOOLEAN", 118);
      kCX = new a("USERFINO_IPCALL_HAS_ENTRY_BOOLEAN", 119);
      kCY = new a("USERFINO_IPCALL_HAS_ENTRY_FIND_REDDOT_INT", 120);
      kCZ = new a("USERFINO_IPCALL_HAS_ENTRY_FIND_WORDING_STRING", 121);
      kDa = new a("USERFINO_IPCALL_HAS_ENTRY_FIND_REDDOT_NEWXML_BOOLEAN", 122);
      kDb = new a("USERINFO_IPCALL_MSG_CENTER_SHOW_REDDOT_BOOLEAN", 123);
      kDc = new a("USERFINO_IPCALL_MSG_CENTER_SHOW_REDDOT_TYPE_INT", 124);
      kDd = new a("USERFINO_IPCALL_REDDOT_RECHARGE_VERSION_INT", 125);
      kDe = new a("USERFINO_IPCALL_SHOW_FROM_VOIP_LAST_TIME_LONG", 126);
      kDf = new a("USERFINO_IPCALL_SHOW_FROM_VOIP_TIME_COUNT_INT", 127);
      kDg = new a("USERINFO_SUBMENU_SHOW_TIT_BOOLEAN", 128);
      kDh = new a("USERINFO_PROFILE_WEIDIANINFO_STRING", 129);
      kDi = new a("GAME_DISCOVERY_ENTRANCE_MSGID_LONG_SYNC", 130);
      kDj = new a("GAME_INDEX_BUBBLE_MSGID_LONG_SYNC", 131);
      kDk = new a("GAME_MSG_ENTRANCE_MSGID_LONG_SYNC", 132);
      kDl = new a("GAME_GIFT_ENTRANCE_MSGID_LONG_SYNC", 133);
      kDm = new a("GAME_INDEX_FLOATLAYER_MSGID_LONG_SYNC", 134);
      kDn = new a("USERINFO_WELCOMEMSG_CONTENT_STRING", 135);
      kDo = new a("USERINFO_WELCOMEMSG_EXT_LASTTIME_LONG", 136);
      kDp = new a("USERINFO_WELCOMEMSG_EXT_SHOWCOUNT_LONG", 137);
      kDq = new a("USERINFO_RES_DOWNLOADER_CHECK_RES_UPDATE_INTERVAL_LONG", 138);
      kDr = new a("USERINFO_RES_DOWNLOADER_CHECK_RESUME_INTERVAL_LONG", 139);
      kDs = new a("USERINFO_LOAN_ENTRANCE_RED_POINT_INT", 140);
      kDt = new a("USERINFO_WEBVIEW_CLEAR_HOST_COOKIES_INTERVAL_LONG", 141);
      kDu = new a("USERINFO_IBEACON_PUSH_SHOP_ID_LONG", 142);
      kDv = new a("USERINFO_IBEACON_PUSH_CHANNEL_OPEN_METHOD_INT", 143);
      kDw = new a("USERINFO_IBEACON_PUSH_CHANNEL_OPEN_TIME_LONG", 144);
      kDx = new a("USERINFO_IBEACON_SHAKE_TAB_DISPLAY_INT", 145);
      kDy = new a("USERINFO_IBEACON_SHAKE_IS_RANGING_INTERFACE_BOOLEAN", 146);
      kDz = new a("USERINFO_IBEACON_PUSH_BEACONINFO_STRING", 147);
      kDA = new a("USERINFO_IBEACON_PUSH_LAST_BEACONINFO_STRING", 148);
      kDB = new a("USERINFO_IBEACON_PUSH_IS_OPEN_BOOLEAN", 149);
      kDC = new a("USERINFO_IBEACON_PUSH_OPEN_TIEMSTAMP_LONG", 150);
      kDD = new a("USERINFO_IBEACON_PUSH_IS_IN_SHAKEUI_BOOLEAN", 151);
      kDE = new a("USERINFO_IBEACON_SHAKE_TAB_IS_BLUETOOTH_RESIDENT_BOOLEAN", 152);
      kDF = new a("USERINFO_IBEACON_SHAKE_TAB_IS_CITY_RESIDENT_BOOLEAN", 153);
      kDG = new a("USERINFO_IBEACON_SHAKE_TAB_IS_UIN_RESIDENT_INT", 154);
      kDH = new a("USERINFO_IBEACON_SHAKE_TAB_RESIDENT_GATED_LAUNCH_INT", 155);
      kDI = new a("USERINFO_PROFILE_WEIDIANINFO_ALERT_INT", 156);
      kDJ = new a("USERINFO_LAST_LOCATION_STRING", 157);
      kDK = new a("USERINFO_LAST_F2F_INVITE_TIME_LONG", 158);
      kDL = new a("USERINFO_F2F_DELAY_TIME_LONG", 159);
      kDM = new a("USERINFO_MALL_INDEX_TYPE_NAME_LIST_STRING_SYNC", 160);
      kDN = new a("USERINFO_MALL_THIRD_PARTY_DISCLAIMER_STRING", 161);
      kDO = new a("USERINFO_SHAKE_TV_ACCURACY_STRING", 162);
      kDP = new a("USERINFO_IPCALL_ACCOUNT_CACHE_STRING", 163);
      kDQ = new a("USERINFO_SET_CAN_WEBVIEW_CACHE_DOWNLOAD_BOOLEAN", 164);
      kDR = new a("USERINFO_SET_CAN_WEBVIEW_CACHE_PRE_PUSH_DOWNLOAD_BOOLEAN", 165);
      kDS = new a("USERINFO_WEBVIEW_CACHE_CLEANUP_INTERVAL_LONG", 166);
      kDT = new a("USERINFO_TRICK_SOTER_BOOLEAN", 167);
      kDU = new a("USERINFO_CLEANUI_QQMGRINFO_STRING", 168);
      kDV = new a("USERINFO_POSITION_AT_CHATRECORD_FIRST_IN_BOOLEAN", 169);
      kDW = new a("USERINFO_HAD_SHOW_WALLET_MULTI_WALLET_GUIDE_BOOLEAN", 170);
      kDX = new a("USERINFO_WALLET_BULLETIN_GET_TIME_LONG", 171);
      kDY = new a("USERINFO_WALLET_BULLETIN_UPDATE_INTERVAL_LONG", 172);
      kDZ = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRL_STRING_SYNC", 173);
      kEa = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_TIP_STRING_SYNC", 174);
      kEb = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKFINDMORE_STRING_SYNC", 175);
      kEc = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKCAMERA_STRING_SYNC", 176);
      kEd = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKFULLSCREEN_STRING_SYNC", 177);
      kEe = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLLUCKYOPEN_BOOLEAN_SYNC", 178);
      kEf = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLLUCKYCTRLHASSHOW_BOOLEAN_SYNC", 179);
      kEg = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLLUCKYCOUNT_INT_SYNC", 180);
      kEh = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLLUCKYCOUNT2_INT_SYNC", 181);
      kEi = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKPOST_STRING_SYNC", 182);
      kEj = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKGOLDCAMERATIP_STRING_SYNC", 183);
      kEk = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_TIPMARKCAMERATIP_STRING_SYNC", 184);
      kEl = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_LEVELCTRL_STRING_SYNC", 185);
      kEm = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_FLOW_CONTROL_CACHEBUFFER_STRING", 186);
      kEn = new a("USERINFO_NEWYEAR_2016_ACCEPT_CARD_ITEM_BUFFER_STRING_SYNC", 187);
      kEo = new a("USERINFO_NEWYEAR_2016_HONGBAO_IS_OPEN_SNS_PAY_INT_SYNC", 188);
      kEp = new a("USERINFO_NEWYEAR_2016_HONGBAO_CAN_OPEN_SNS_PAY_INT_SYNC", 189);
      kEq = new a("USERINFO_NEWYEAR_2016_HONGBAO_IS_WHITE_USER_INT_SYNC", 190);
      kEr = new a("USERINFO_NEWYEAR_2016_HONGBAO_OPEN_SNS_PAY_TITLE_STRING_SYNC", 191);
      kEs = new a("USERINFO_NEWYEAR_2016_HONGBAO_OPEN_SNS_PAY_WORDING_STRING_SYNC", 192);
      kEt = new a("USERINFO_NEWYEAR_2016_HONGBAO_SET_SNS_PAY_TITLE_STRING_SYNC", 193);
      kEu = new a("USERINFO_NEWYEAR_2016_HONGBAO_SET_SNS_PAY_WORDING_STRING_SYNC", 194);
      kEv = new a("USERINFO_NEWYEAR_2016_HONGBAO_HAS_SHOW_SNS_PAY_GUIDE_DIALOG_BOOLEAN_SYNC", 195);
      kEw = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_PATH_STRING_SYNC", 196);
      kEx = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_ID_STRING_SYNC", 197);
      kEy = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_AES_KEY_STRING_SYNC", 198);
      kEz = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_LENGTH_INT_SYNC", 199);
    }
    
    private a() {}
  }
}

/* Location:
 * Qualified Name:     com.tencent.mm.storage.j
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */