package com.tencent.mm.svg.a.a;

import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.Paint.Cap;
import android.graphics.Paint.Join;
import android.graphics.Paint.Style;
import android.graphics.Path;
import android.os.Looper;
import com.tencent.mm.svg.WeChatSVGRenderC2Java;
import com.tencent.mm.svg.c;

public final class ad
  extends c
{
  private final int height = 54;
  private final int width = 54;
  
  protected final int h(int paramInt, Object... paramVarArgs)
  {
    switch (paramInt)
    {
    }
    for (;;)
    {
      return 0;
      return 54;
      return 54;
      Canvas localCanvas = (Canvas)paramVarArgs[0];
      paramVarArgs = (Looper)paramVarArgs[1];
      c.e(paramVarArgs);
      c.d(paramVarArgs);
      Paint localPaint = c.h(paramVarArgs);
      localPaint.setFlags(385);
      localPaint.setStyle(Paint.Style.FILL);
      Object localObject1 = c.h(paramVarArgs);
      ((Paint)localObject1).setFlags(385);
      ((Paint)localObject1).setStyle(Paint.Style.STROKE);
      localPaint.setColor(-16777216);
      ((Paint)localObject1).setStrokeWidth(1.0F);
      ((Paint)localObject1).setStrokeCap(Paint.Cap.BUTT);
      ((Paint)localObject1).setStrokeJoin(Paint.Join.MITER);
      ((Paint)localObject1).setStrokeMiter(4.0F);
      ((Paint)localObject1).setPathEffect(null);
      Object localObject2 = c.a((Paint)localObject1, paramVarArgs);
      ((Paint)localObject2).set((Paint)localObject1);
      ((Paint)localObject2).setStrokeWidth(1.0F);
      localObject1 = c.a(localPaint, paramVarArgs);
      ((Paint)localObject1).set(localPaint);
      ((Paint)localObject1).setColor(-9145228);
      localCanvas.save();
      localPaint = c.a((Paint)localObject1, paramVarArgs);
      localPaint.set((Paint)localObject1);
      localObject2 = c.i(paramVarArgs);
      ((Path)localObject2).moveTo(0.0F, 0.0F);
      ((Path)localObject2).lineTo(17.995556F, 0.0F);
      ((Path)localObject2).cubicTo(17.995556F, 5.998519F, 18.005554F, 11.997038F, 17.995556F, 17.995556F);
      ((Path)localObject2).cubicTo(11.997038F, 18.005554F, 5.998519F, 17.995556F, 0.0F, 17.995556F);
      ((Path)localObject2).lineTo(0.0F, 0.0F);
      ((Path)localObject2).lineTo(0.0F, 0.0F);
      ((Path)localObject2).close();
      ((Path)localObject2).moveTo(6.0F, 6.0F);
      ((Path)localObject2).lineTo(6.0F, 12.0F);
      ((Path)localObject2).lineTo(12.0F, 12.0F);
      ((Path)localObject2).lineTo(12.0F, 6.0F);
      ((Path)localObject2).lineTo(6.0F, 6.0F);
      ((Path)localObject2).lineTo(6.0F, 6.0F);
      ((Path)localObject2).close();
      WeChatSVGRenderC2Java.setFillType((Path)localObject2, 2);
      localCanvas.drawPath((Path)localObject2, localPaint);
      localCanvas.restore();
      localCanvas.save();
      localPaint = c.a((Paint)localObject1, paramVarArgs);
      localPaint.set((Paint)localObject1);
      localObject2 = c.i(paramVarArgs);
      ((Path)localObject2).moveTo(24.0F, 0.0F);
      ((Path)localObject2).lineTo(36.0F, 0.0F);
      ((Path)localObject2).lineTo(36.0F, 6.0F);
      ((Path)localObject2).lineTo(42.0F, 6.0F);
      ((Path)localObject2).lineTo(42.0F, 12.0F);
      ((Path)localObject2).lineTo(30.0F, 12.0F);
      ((Path)localObject2).lineTo(30.0F, 6.01F);
      ((Path)localObject2).cubicTo(28.0F, 6.0F, 26.0F, 6.0F, 24.0F, 5.99F);
      ((Path)localObject2).lineTo(24.0F, 0.0F);
      ((Path)localObject2).lineTo(24.0F, 0.0F);
      ((Path)localObject2).close();
      WeChatSVGRenderC2Java.setFillType((Path)localObject2, 2);
      localCanvas.drawPath((Path)localObject2, localPaint);
      localCanvas.restore();
      localCanvas.save();
      localPaint = c.a((Paint)localObject1, paramVarArgs);
      localPaint.set((Paint)localObject1);
      localObject2 = c.i(paramVarArgs);
      ((Path)localObject2).moveTo(42.0F, 0.0F);
      ((Path)localObject2).lineTo(54.0F, 0.0F);
      ((Path)localObject2).lineTo(54.0F, 24.0F);
      ((Path)localObject2).lineTo(48.01F, 24.0F);
      ((Path)localObject2).cubicTo(48.0F, 22.0F, 48.0F, 20.0F, 47.99F, 18.0F);
      ((Path)localObject2).lineTo(42.0F, 18.0F);
      ((Path)localObject2).lineTo(42.0F, 12.0F);
      ((Path)localObject2).lineTo(48.0F, 12.0F);
      ((Path)localObject2).lineTo(48.0F, 6.0F);
      ((Path)localObject2).lineTo(42.0F, 6.0F);
      ((Path)localObject2).lineTo(42.0F, 0.0F);
      ((Path)localObject2).lineTo(42.0F, 0.0F);
      ((Path)localObject2).close();
      WeChatSVGRenderC2Java.setFillType((Path)localObject2, 2);
      localCanvas.drawPath((Path)localObject2, localPaint);
      localCanvas.restore();
      localCanvas.save();
      localPaint = c.a((Paint)localObject1, paramVarArgs);
      localPaint.set((Paint)localObject1);
      localObject2 = c.i(paramVarArgs);
      ((Path)localObject2).moveTo(24.0F, 12.0F);
      ((Path)localObject2).lineTo(30.0F, 12.0F);
      ((Path)localObject2).lineTo(30.0F, 18.0F);
      ((Path)localObject2).lineTo(24.0F, 18.0F);
      ((Path)localObject2).lineTo(24.0F, 12.0F);
      ((Path)localObject2).lineTo(24.0F, 12.0F);
      ((Path)localObject2).close();
      WeChatSVGRenderC2Java.setFillType((Path)localObject2, 2);
      localCanvas.drawPath((Path)localObject2, localPaint);
      localCanvas.restore();
      localCanvas.save();
      localPaint = c.a((Paint)localObject1, paramVarArgs);
      localPaint.set((Paint)localObject1);
      localObject2 = c.i(paramVarArgs);
      ((Path)localObject2).moveTo(30.0F, 18.0F);
      ((Path)localObject2).lineTo(42.0F, 18.0F);
      ((Path)localObject2).lineTo(42.0F, 24.0F);
      ((Path)localObject2).lineTo(36.0F, 24.0F);
      ((Path)localObject2).lineTo(36.0F, 30.0F);
      ((Path)localObject2).lineTo(24.0F, 30.0F);
      ((Path)localObject2).lineTo(24.0F, 36.0F);
      ((Path)localObject2).lineTo(12.0F, 36.0F);
      ((Path)localObject2).lineTo(12.0F, 30.0F);
      ((Path)localObject2).lineTo(18.0F, 30.0F);
      ((Path)localObject2).lineTo(18.0F, 24.0F);
      ((Path)localObject2).lineTo(30.0F, 24.0F);
      ((Path)localObject2).lineTo(30.0F, 18.0F);
      ((Path)localObject2).lineTo(30.0F, 18.0F);
      ((Path)localObject2).close();
      WeChatSVGRenderC2Java.setFillType((Path)localObject2, 2);
      localCanvas.drawPath((Path)localObject2, localPaint);
      localCanvas.restore();
      localCanvas.save();
      localPaint = c.a((Paint)localObject1, paramVarArgs);
      localPaint.set((Paint)localObject1);
      localObject2 = c.i(paramVarArgs);
      ((Path)localObject2).moveTo(0.0F, 24.0F);
      ((Path)localObject2).lineTo(12.0F, 24.0F);
      ((Path)localObject2).lineTo(12.0F, 30.0F);
      ((Path)localObject2).lineTo(6.0F, 30.0F);
      ((Path)localObject2).lineTo(6.0F, 36.0F);
      ((Path)localObject2).lineTo(0.0F, 36.0F);
      ((Path)localObject2).lineTo(0.0F, 24.0F);
      ((Path)localObject2).lineTo(0.0F, 24.0F);
      ((Path)localObject2).close();
      WeChatSVGRenderC2Java.setFillType((Path)localObject2, 2);
      localCanvas.drawPath((Path)localObject2, localPaint);
      localCanvas.restore();
      localCanvas.save();
      localPaint = c.a((Paint)localObject1, paramVarArgs);
      localPaint.set((Paint)localObject1);
      localObject2 = c.i(paramVarArgs);
      ((Path)localObject2).moveTo(36.0F, 30.0F);
      ((Path)localObject2).lineTo(42.0F, 30.0F);
      ((Path)localObject2).lineTo(42.0F, 36.0F);
      ((Path)localObject2).lineTo(36.0F, 36.0F);
      ((Path)localObject2).lineTo(36.0F, 30.0F);
      ((Path)localObject2).lineTo(36.0F, 30.0F);
      ((Path)localObject2).close();
      WeChatSVGRenderC2Java.setFillType((Path)localObject2, 2);
      localCanvas.drawPath((Path)localObject2, localPaint);
      localCanvas.restore();
      localCanvas.save();
      localPaint = c.a((Paint)localObject1, paramVarArgs);
      localPaint.set((Paint)localObject1);
      localObject2 = c.i(paramVarArgs);
      ((Path)localObject2).moveTo(48.0F, 30.0F);
      ((Path)localObject2).lineTo(54.0F, 30.0F);
      ((Path)localObject2).lineTo(54.0F, 42.0F);
      ((Path)localObject2).lineTo(48.0F, 42.0F);
      ((Path)localObject2).lineTo(48.0F, 48.0F);
      ((Path)localObject2).lineTo(54.0F, 48.0F);
      ((Path)localObject2).lineTo(54.0F, 54.0F);
      ((Path)localObject2).lineTo(42.0F, 54.0F);
      ((Path)localObject2).lineTo(42.0F, 48.0F);
      ((Path)localObject2).lineTo(36.0F, 48.0F);
      ((Path)localObject2).lineTo(36.0F, 42.0F);
      ((Path)localObject2).lineTo(42.0F, 42.0F);
      ((Path)localObject2).lineTo(42.0F, 36.0F);
      ((Path)localObject2).lineTo(47.99F, 36.0F);
      ((Path)localObject2).cubicTo(48.0F, 34.0F, 48.0F, 32.0F, 48.0F, 30.0F);
      ((Path)localObject2).lineTo(48.0F, 30.0F);
      ((Path)localObject2).close();
      WeChatSVGRenderC2Java.setFillType((Path)localObject2, 2);
      localCanvas.drawPath((Path)localObject2, localPaint);
      localCanvas.restore();
      localCanvas.save();
      localPaint = c.a((Paint)localObject1, paramVarArgs);
      localPaint.set((Paint)localObject1);
      localObject2 = c.i(paramVarArgs);
      ((Path)localObject2).moveTo(6.0F, 36.0F);
      ((Path)localObject2).lineTo(12.0F, 36.0F);
      ((Path)localObject2).lineTo(12.0F, 42.0F);
      ((Path)localObject2).lineTo(6.0F, 42.0F);
      ((Path)localObject2).lineTo(6.0F, 36.0F);
      ((Path)localObject2).lineTo(6.0F, 36.0F);
      ((Path)localObject2).close();
      WeChatSVGRenderC2Java.setFillType((Path)localObject2, 2);
      localCanvas.drawPath((Path)localObject2, localPaint);
      localCanvas.restore();
      localCanvas.save();
      localPaint = c.a((Paint)localObject1, paramVarArgs);
      localPaint.set((Paint)localObject1);
      localObject2 = c.i(paramVarArgs);
      ((Path)localObject2).moveTo(24.0F, 36.0F);
      ((Path)localObject2).lineTo(36.0F, 36.0F);
      ((Path)localObject2).lineTo(36.0F, 42.0F);
      ((Path)localObject2).lineTo(24.0F, 42.0F);
      ((Path)localObject2).lineTo(24.0F, 36.0F);
      ((Path)localObject2).lineTo(24.0F, 36.0F);
      ((Path)localObject2).close();
      WeChatSVGRenderC2Java.setFillType((Path)localObject2, 2);
      localCanvas.drawPath((Path)localObject2, localPaint);
      localCanvas.restore();
      localCanvas.save();
      localPaint = c.a((Paint)localObject1, paramVarArgs);
      localPaint.set((Paint)localObject1);
      localObject2 = c.i(paramVarArgs);
      ((Path)localObject2).moveTo(0.0F, 42.0F);
      ((Path)localObject2).lineTo(6.0F, 42.0F);
      ((Path)localObject2).lineTo(6.0F, 48.0F);
      ((Path)localObject2).lineTo(18.0F, 48.0F);
      ((Path)localObject2).lineTo(18.0F, 54.0F);
      ((Path)localObject2).lineTo(0.0F, 54.0F);
      ((Path)localObject2).lineTo(0.0F, 42.0F);
      ((Path)localObject2).lineTo(0.0F, 42.0F);
      ((Path)localObject2).close();
      WeChatSVGRenderC2Java.setFillType((Path)localObject2, 2);
      localCanvas.drawPath((Path)localObject2, localPaint);
      localCanvas.restore();
      localCanvas.save();
      localPaint = c.a((Paint)localObject1, paramVarArgs);
      localPaint.set((Paint)localObject1);
      localObject2 = c.i(paramVarArgs);
      ((Path)localObject2).moveTo(18.0F, 42.0F);
      ((Path)localObject2).lineTo(24.0F, 42.0F);
      ((Path)localObject2).lineTo(24.0F, 48.0F);
      ((Path)localObject2).lineTo(18.0F, 48.0F);
      ((Path)localObject2).lineTo(18.0F, 42.0F);
      ((Path)localObject2).lineTo(18.0F, 42.0F);
      ((Path)localObject2).close();
      WeChatSVGRenderC2Java.setFillType((Path)localObject2, 2);
      localCanvas.drawPath((Path)localObject2, localPaint);
      localCanvas.restore();
      localCanvas.save();
      localPaint = c.a((Paint)localObject1, paramVarArgs);
      localPaint.set((Paint)localObject1);
      localObject1 = c.i(paramVarArgs);
      ((Path)localObject1).moveTo(24.0F, 48.0F);
      ((Path)localObject1).lineTo(36.0F, 48.0F);
      ((Path)localObject1).lineTo(36.0F, 54.0F);
      ((Path)localObject1).lineTo(24.0F, 54.0F);
      ((Path)localObject1).lineTo(24.0F, 48.0F);
      ((Path)localObject1).lineTo(24.0F, 48.0F);
      ((Path)localObject1).close();
      WeChatSVGRenderC2Java.setFillType((Path)localObject1, 2);
      localCanvas.drawPath((Path)localObject1, localPaint);
      localCanvas.restore();
      c.g(paramVarArgs);
    }
  }
}

/* Location:
 * Qualified Name:     com.tencent.mm.svg.a.a.ad
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */